import { A, B, D, N, S, X, defineCollection, ref } from './fields.js';
import type { Registry } from './fields.js';

/**
 * Per-society (tenant) database collections.
 *
 * Every society gets its own database (§4: "New DB instance for each new registered
 * society"). Consequently `societyId` is technically redundant inside a tenant DB — it is
 * kept on every record anyway and *verified* on every read, so that:
 *   1. a mis-routed connection can never silently serve another society's data,
 *   2. backup/restore or a future migration to a shared database stays lossless,
 *   3. audit exports are self-describing.
 *
 * Naming follows §53 exactly (users, roles, societies, buildings, wings, floors, units,
 * unit_members, residents, family_members, vehicles, parking_slots, visitors,
 * visitor_passes, visitor_entries, deliveries, staff, staff_attendance, vendors,
 * complaints, complaint_comments, work_orders, amenities, amenity_slots,
 * amenity_bookings, notices, events, event_registrations, polls, poll_options,
 * poll_votes, maintenance_bills, bill_items, payments, payment_transactions, ledgers,
 * journal_entries, expenses, incomes, documents, notifications, emergency_alerts,
 * audit_logs, subscriptions …).
 */
export const TENANT_COLLECTIONS: Registry = {
  /* ------------------------------- identity ------------------------------- */

  users: defineCollection('users', {
    fullName: S({ required: true, trim: true }),
    email: S({ lowercase: true, trim: true, sparse: true }),
    phone: S({ index: true, trim: true }),
    passwordHash: S({ description: 'bcrypt — never serialised' }),
    avatarUrl: S(),
    gender: S({ enum: ['MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY'] }),
    dateOfBirth: D(),
    roles: A({ required: true, description: 'Role keys granted in THIS society' }),
    /** Denormalised permission set, recomputed when roles/permissions change (fast authz). */
    permissions: A({ default: () => [] }),
    residentId: ref('residents'),
    staffId: ref('staff'),
    vendorId: ref('vendors'),
    unitIds: A({ description: 'Units this user is linked to (residents, staff with unit access)' }),
    primaryUnitId: ref('units'),
    gateIds: A({ description: 'Gates a guard is assigned to' }),
    status: S({ enum: ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'INVITED', 'LOCKED'], default: 'ACTIVE', index: true }),
    isPrimaryContact: B({ default: false }),
    lastLoginAt: D(),
    lastLoginIp: S(),
    failedLoginAttempts: N({ default: 0 }),
    lockedUntil: D(),
    mustChangePassword: B({ default: false }),
    appPinHash: S({ description: 'Optional app-level PIN (§74)' }),
    biometricEnabled: B({ default: false }),
    preferences: X({
      default: () => ({
        language: 'en',
        pushEnabled: true,
        emailEnabled: true,
        smsEnabled: false,
        visitorApprovalAlerts: true,
        deliveryAlerts: true,
        staffArrivalAlerts: false,
        quietHours: null,
      }),
    }),
    invitationTokenHash: S(),
    invitationSentAt: D(),
    invitationAcceptedAt: D(),
    metadata: X(),
  }, {
    indexes: [
      { fields: { societyId: 1, phone: 1 }, unique: true, sparse: true },
      { fields: { societyId: 1, email: 1 }, unique: true, sparse: true },
      { fields: { societyId: 1, status: 1 } },
    ],
    description: 'A person who can authenticate into this society. One document per (society, person).',
  }),

  /** Cross-society identity: the same human in two societies has one `identity`. */
  identities: defineCollection('identities', {
    phone: S({ required: true, unique: true }),
    email: S({ lowercase: true }),
    fullName: S(),
    globalUserId: S({ index: true, description: 'Stable id shared across societies' }),
    linkedUserIds: A(),
    consentVersion: S(),
    consentAt: D(),
    isBlocked: B({ default: false }),
  }, { indexes: [{ fields: { phone: 1 }, unique: true }] }),

  /** Refresh tokens / device sessions for society users (§7 device & session management). */
  sessions: defineCollection('sessions', {
    userId: ref('users', { required: true }),
    refreshTokenHash: S({ required: true, index: true }),
    tokenFamily: S({ required: true, index: true }),
    deviceId: S({ index: true }),
    deviceName: S(),
    platform: S({ enum: ['ios', 'android', 'web', 'unknown'], default: 'web' }),
    appVersion: S(),
    osVersion: S(),
    model: S(),
    pushToken: S(),
    pushProvider: S(),
    userAgent: S(),
    ip: S(),
    lastUsedAt: D(),
    lastUsedIp: S(),
    expiresAt: D({ required: true, index: true }),
    revokedAt: D(),
    revokeReason: S(),
    isActive: B({ default: true, index: true }),
  }, {
    indexes: [
      { fields: { userId: 1, isActive: 1 } },
      { fields: { tokenFamily: 1 } },
      { fields: { expiresAt: 1 }, expireAfterSeconds: 0 },
      { fields: { societyId: 1, deviceId: 1 } },
    ],
  }),

  /** Role definitions + per-society permission overrides (§6 configurable permissions). */
  roles: defineCollection('roles', {
    role: S({ required: true }),
    label: S({ required: true }),
    scope: S({ required: true, enum: ['platform', 'society', 'resident', 'security', 'staff', 'vendor'] }),
    permissions: A({ default: () => [] }),
    /** Permissions removed from the platform default for this society. */
    revokedPermissions: A({ default: () => [] }),
    isSystem: B({ default: true }),
    isCustom: B({ default: false }),
    description: S(),
    updatedBy: ref('users'),
  }, {
    indexes: [{ fields: { societyId: 1, role: 1 }, unique: true }, { fields: { societyId: 1, scope: 1 } }],
  }),

  /** This society's configuration (§63 — no business rule is hard-coded). */
  society_settings: defineCollection('society_settings', {
    key: S({ required: true, unique: true, description: 'One document per settings namespace' }),
    value: X({ required: true }),
    description: S(),
    updatedBy: ref('users'),
  }, { indexes: [{ fields: { societyId: 1, key: 1 }, unique: true }] }),

  /* ------------------------------ hierarchy ------------------------------ */

  buildings: defineCollection('buildings', {
    name: S({ required: true, trim: true }),
    code: S({ required: true, trim: true }),
    type: S({ enum: ['TOWER', 'BUILDING', 'BLOCK', 'VILLA_ROW', 'COMMERCIAL'], default: 'TOWER' }),
    totalFloors: N({ default: 1 }),
    unitsPerFloor: N({ default: 0 }),
    hasWings: B({ default: false }),
    address: X(),
    yearBuilt: N(),
    liftCount: N({ default: 0 }),
    isActive: B({ default: true }),
    unitCount: N({ default: 0, description: 'Denormalised counter maintained by the units service' }),
    order: N({ default: 0 }),
  }, { indexes: [{ fields: { societyId: 1, code: 1 }, unique: true }, { fields: { societyId: 1, isActive: 1 } }] }),

  wings: defineCollection('wings', {
    buildingId: ref('buildings', { required: true }),
    name: S({ required: true, trim: true }),
    code: S({ required: true, trim: true }),
    totalFloors: N({ default: 1 }),
    isActive: B({ default: true }),
    unitCount: N({ default: 0 }),
    order: N({ default: 0 }),
  }, { indexes: [{ fields: { societyId: 1, buildingId: 1, code: 1 }, unique: true }] }),

  floors: defineCollection('floors', {
    buildingId: ref('buildings', { required: true }),
    wingId: ref('wings'),
    number: N({ required: true }),
    name: S(),
    isActive: B({ default: true }),
    unitCount: N({ default: 0 }),
  }, { indexes: [{ fields: { societyId: 1, buildingId: 1, wingId: 1, number: 1 }, unique: true }] }),

  units: defineCollection('units', {
    buildingId: ref('buildings', { required: true }),
    wingId: ref('wings'),
    floorId: ref('floors'),
    floorNumber: N({ default: 0 }),
    unitNumber: S({ required: true, trim: true }),
    /** Human readable label: "A-101, Tower A". */
    label: S({ index: true }),
    type: S({ enum: ['FLAT', 'APARTMENT', 'VILLA', 'BUNGALOW', 'PENTHOUSE', 'STUDIO', 'SHOP', 'OFFICE', 'WAREHOUSE', 'PARKING_UNIT'], default: 'FLAT' }),
    carpetAreaSqft: N(),
    builtUpAreaSqft: N(),
    bedrooms: N(),
    bathrooms: N(),
    balconies: N(),
    status: S({ enum: ['VACANT', 'OCCUPIED', 'LOCKED', 'UNDER_MAINTENANCE'], default: 'VACANT', index: true }),
    occupancyType: S({ enum: ['OWNER', 'TENANT', 'OWNER_AND_TENANT', 'VACANT', 'COMPANY'], default: 'VACANT', index: true }),
    parkingSlotIds: A(),
    maintenanceRate: N({ description: 'Overrides the society default when set' }),
    waterCharge: N({ default: 0 }),
    parkingCharge: N({ default: 0 }),
    isActive: B({ default: true }),
    /** Denormalised counters keep unit lists fast for 10,000+ unit societies (§60). */
    ownerCount: N({ default: 0 }),
    tenantCount: N({ default: 0 }),
    familyCount: N({ default: 0 }),
    vehicleCount: N({ default: 0 }),
    outstandingAmount: N({ default: 0, description: 'Cached unpaid bill total, refreshed on payment' }),
  }, {
    indexes: [
      { fields: { societyId: 1, buildingId: 1, wingId: 1, unitNumber: 1 }, unique: true },
      { fields: { societyId: 1, status: 1 } },
      { fields: { societyId: 1, label: 1 } },
    ],
  }),

  /** The unit ⇄ person link. One resident can hold several units; one unit has many members. */
  unit_members: defineCollection('unit_members', {
    unitId: ref('units', { required: true }),
    residentId: ref('residents', { required: true }),
    userId: ref('users'),
    kind: S({ enum: ['OWNER', 'TENANT', 'FAMILY', 'COMPANY_GUEST'], required: true, index: true }),
    isPrimary: B({ default: false }),
    moveInDate: D(),
    moveOutDate: D(),
    isActive: B({ default: true, index: true }),
    permissions: X({ default: () => ({}) }),
  }, { indexes: [{ fields: { societyId: 1, unitId: 1, residentId: 1 }, unique: true }, { fields: { societyId: 1, residentId: 1 } }] }),

  residents: defineCollection('residents', {
    fullName: S({ required: true, trim: true }),
    phone: S({ required: true, index: true }),
    email: S({ lowercase: true }),
    userId: ref('users'),
    gender: S(),
    dateOfBirth: D(),
    photoUrl: S(),
    address: X(),
    /** Primary unit; additional units live in `unit_members`. */
    unitId: ref('units'),
    kind: S({ enum: ['OWNER', 'TENANT', 'FAMILY', 'COMPANY_GUEST'], default: 'OWNER', index: true }),
    isPrimary: B({ default: false }),
    moveInDate: D(),
    moveOutDate: D(),
    emergencyContactName: S(),
    emergencyContactPhone: S(),
    emergencyContactRelation: S(),
    occupation: S(),
    bloodGroup: S(),
    idProofType: S(),
    idProofNumber: S({ description: 'Stored, never returned in list responses' }),
    ownerName: S({ description: 'Tenant-only: the landlord name' }),
    leaseStartDate: D(),
    leaseEndDate: D(),
    rentAmount: N(),
    status: S({ enum: ['ACTIVE', 'MOVED_OUT', 'INACTIVE'], default: 'ACTIVE', index: true }),
    isActive: B({ default: true }),
    tags: A(),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, kind: 1 } },
      { fields: { societyId: 1, phone: 1 } },
      { fields: { societyId: 1, fullName: 1 } },
    ],
  }),

  family_members: defineCollection('family_members', {
    parentResidentId: ref('residents', { required: true, description: 'The resident who added this member' }),
    unitId: ref('units', { required: true }),
    userId: ref('users', { description: 'Set once the family member is allowed to log in' }),
    fullName: S({ required: true, trim: true }),
    relationship: S({ enum: ['SPOUSE', 'CHILD', 'PARENT', 'SIBLING', 'GRANDPARENT', 'IN_LAW', 'OTHER'], default: 'OTHER' }),
    phone: S(),
    email: S({ lowercase: true }),
    age: N(),
    dateOfBirth: D(),
    gender: S(),
    photoUrl: S(),
    emergencyContactName: S(),
    emergencyContactPhone: S(),
    /** Configurable per-member access (§9). */
    permissions: X({
      default: () => ({
        canApproveVisitors: false,
        canApproveDeliveries: false,
        canRaiseComplaints: true,
        canBookAmenities: false,
        canMakePayments: false,
        canViewBills: false,
        canAddStaff: false,
        canRaiseEmergency: true,
      }),
    }),
    canLogin: B({ default: false }),
    isActive: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, unitId: 1 } }, { fields: { societyId: 1, parentResidentId: 1 } }] }),

  /* ------------------------- vehicles & parking -------------------------- */

  vehicles: defineCollection('vehicles', {
    /** Normalised plate (upper-case, no spaces) — the unique key used by gate lookups. */
    vehicleNumber: S({ required: true, index: true }),
    displayNumber: S(),
    type: S({ enum: ['CAR', 'BIKE', 'SCOOTER', 'EV_CAR', 'EV_BIKE', 'COMMERCIAL', 'AUTO', 'CYCLE', 'OTHER'], default: 'CAR' }),
    brand: S(),
    model: S(),
    color: S(),
    year: N(),
    unitId: ref('units'),
    residentId: ref('residents'),
    staffId: ref('staff'),
    parkingSlotId: ref('parking_slots'),
    isEv: B({ default: false }),
    stickerNumber: S({ index: true }),
    /** Secure QR token id for the vehicle sticker (§57). */
    qrPassId: ref('visitor_passes'),
    insuranceExpiry: D(),
    rcExpiry: D(),
    isPrimary: B({ default: false }),
    isActive: B({ default: true }),
  }, {
    indexes: [
      { fields: { societyId: 1, vehicleNumber: 1 } },
      { fields: { societyId: 1, unitId: 1 } },
      { fields: { societyId: 1, qrPassId: 1 } },
    ],
  }),

  parking_areas: defineCollection('parking_areas', {
    name: S({ required: true }),
    code: S({ required: true }),
    level: S(),
    buildingId: ref('buildings'),
    capacity: N({ default: 0 }),
    isActive: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, code: 1 }, unique: true }] }),

  parking_slots: defineCollection('parking_slots', {
    areaId: ref('parking_areas'),
    slotNumber: S({ required: true }),
    type: S({ enum: ['RESERVED', 'VISITOR', 'EV', 'STAFF', 'TWO_WHEELER', 'DISABLED', 'COMMON'], default: 'RESERVED', index: true }),
    status: S({ enum: ['AVAILABLE', 'OCCUPIED', 'RESERVED', 'VISITOR', 'MAINTENANCE', 'BLOCKED'], default: 'AVAILABLE', index: true }),
    capacity: N({ default: 1 }),
    isEv: B({ default: false }),
    hasCharger: B({ default: false }),
    monthlyCharge: N({ default: 0 }),
    buildingId: ref('buildings'),
    assignedUnitId: ref('units'),
    assignedVehicleId: ref('vehicles'),
    assignedFrom: D(),
    assignedTill: D(),
    isActive: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, areaId: 1, slotNumber: 1 }, unique: true }, { fields: { societyId: 1, assignedUnitId: 1 } }] }),

  /* ------------------------------- security ------------------------------ */

  gates: defineCollection('gates', {
    name: S({ required: true }),
    code: S({ required: true }),
    type: S({ enum: ['MAIN', 'SECONDARY', 'SERVICE', 'PARKING', 'PEDESTRIAN', 'EMERGENCY'], default: 'MAIN' }),
    allowsVehicles: B({ default: true }),
    allowsPedestrians: B({ default: true }),
    isOpen24x7: B({ default: true }),
    openTime: S(),
    closeTime: S(),
    location: X(),
    isActive: B({ default: true }),
    /** Denormalised daily counters for the security dashboard. */
    entriesToday: N({ default: 0 }),
    lastEntryAt: D(),
  }, { indexes: [{ fields: { societyId: 1, code: 1 }, unique: true }] }),

  guard_assignments: defineCollection('guard_assignments', {
    staffId: ref('staff', { required: true }),
    userId: ref('users'),
    gateId: ref('gates', { required: true }),
    shift: S({ enum: ['MORNING', 'AFTERNOON', 'NIGHT', 'GENERAL'], default: 'GENERAL', index: true }),
    startDate: D({ required: true }),
    endDate: D(),
    isActive: B({ default: true }),
    notes: S(),
  }, { indexes: [{ fields: { societyId: 1, staffId: 1, gateId: 1, isActive: 1 } }, { fields: { societyId: 1, gateId: 1, shift: 1 } }] }),

  guard_shift_logs: defineCollection('guard_shift_logs', {
    staffId: ref('staff', { required: true }),
    userId: ref('users'),
    gateId: ref('gates', { required: true }),
    shift: S(),
    loginAt: D({ required: true }),
    logoutAt: D(),
    ip: S(),
    deviceId: S(),
    location: X(),
    visitorsHandled: N({ default: 0 }),
    deliveriesHandled: N({ default: 0 }),
    notes: S(),
  }, { indexes: [{ fields: { societyId: 1, staffId: 1, loginAt: -1 } }, { fields: { societyId: 1, gateId: 1, loginAt: -1 } }] }),

  /**
   * Visitor records — the union of pre-approved and at-gate visitors (§11).
   * `source` distinguishes them; `status` drives the approval state machine.
   */
  visitors: defineCollection('visitors', {
    visitorName: S({ required: true, trim: true }),
    visitorPhone: S({ index: true }),
    unitId: ref('units', { required: true }),
    residentId: ref('residents'),
    purpose: S({ required: true }),
    visitorType: S({
      enum: ['GUEST', 'RELATIVE', 'FRIEND', 'CAB', 'PRIVATE_DRIVER', 'DELIVERY', 'COURIER', 'FOOD_DELIVERY', 'GROCERY', 'ECOMMERCE', 'AMAZON', 'SERVICES', 'TECHNICIAN', 'DAILY_HELP', 'PET', 'VENDOR', 'OTHER'],
      default: 'GUEST',
      index: true,
    }),
    source: S({ enum: ['PRE_APPROVED', 'AT_GATE', 'SYSTEM'], default: 'AT_GATE', index: true }),
    status: S({
      enum: ['PRE_APPROVED', 'AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'IGNORED', 'EXPIRED', 'CANCELLED', 'INSIDE', 'EXITED'],
      default: 'AWAITING_APPROVAL',
      index: true,
    }),
    numberOfVisitors: N({ default: 1 }),
    vehicleNumber: S({ index: true }),
    photoUrl: S(),
    idProofType: S(),
    idProofNumber: S(),
    address: S(),
    notes: S(),
    instructions: S(),
    rejectReason: S(),
    /** Pre-approval window. */
    visitDate: D({ index: true, description: 'Local calendar date of the visit' }),
    expectedArrival: D(),
    expectedDeparture: D(),
    /** Actual gate times. */
    entryTime: D({ index: true }),
    exitTime: D(),
    gateId: ref('gates'),
    entryGateId: ref('gates'),
    exitGateId: ref('gates'),
    passId: ref('visitor_passes'),
    decidedBy: ref('users'),
    decidedAt: D(),
    decidedFrom: S({ enum: ['APP', 'WEB', 'SECURITY', 'AUTO', 'TIMEOUT'] }),
    recordedBy: ref('users', { description: 'The guard who captured this at the gate' }),
    location: X(),
    /** Set when a resident does not respond within `visitor.autoExpireMinutes`. */
    autoExpiredAt: D(),
    /** Timeline of every state change — powers the resident & admin activity views. */
    timeline: A(),
    clientRequestId: S({ index: true, description: 'Idempotency key for offline sync (§50)' }),
    syncedAt: D(),
    isOfflineCapture: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, createdAt: -1 } },
      { fields: { societyId: 1, status: 1, createdAt: -1 } },
      { fields: { societyId: 1, visitDate: 1, status: 1 } },
      { fields: { societyId: 1, visitorPhone: 1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
      { fields: { societyId: 1, passId: 1 } },
    ],
  }),

  /**
   * Secure QR passes (§12, §57). The QR image encodes ONLY `token`; everything else stays
   * server-side. `sign` is an HMAC over the canonical claim set, so a pass minted for one
   * society cannot be replayed at another, and tampering invalidates it.
   */
  visitor_passes: defineCollection('visitor_passes', {
    token: S({ required: true, unique: true, description: 'Opaque signed token embedded in the QR' }),
    tokenHash: S({ required: true, index: true, description: 'SHA-256(token) — the value actually looked up' }),
    kind: S({ enum: ['VISITOR', 'VEHICLE', 'STAFF', 'AMENITY_BOOKING', 'SOCIETY_ACCESS'], required: true, index: true }),
    visitorId: ref('visitors'),
    bookingId: ref('amenity_bookings'),
    vehicleId: ref('vehicles'),
    staffId: ref('staff'),
    unitId: ref('units'),
    residentId: ref('residents'),
    status: S({ enum: ['ACTIVE', 'USED', 'EXPIRED', 'REVOKED'], default: 'ACTIVE', index: true }),
    validFrom: D({ required: true }),
    validTill: D({ required: true, index: true }),
    maxEntries: N({ default: 1 }),
    entriesUsed: N({ default: 0 }),
    /** Single-use enforcement: the first scan consumes the pass when `maxEntries` is 1. */
    singleUse: B({ default: true }),
    sign: S({ required: true, description: 'HMAC-SHA256 signature over the canonical claims' }),
    lastScannedAt: D(),
    lastScannedBy: ref('users'),
    lastScannedGateId: ref('gates'),
    revokedAt: D(),
    revokeReason: S(),
    scanCount: N({ default: 0 }),
  }, {
    indexes: [
      { fields: { token: 1 }, unique: true },
      { fields: { societyId: 1, tokenHash: 1 } },
      { fields: { societyId: 1, kind: 1, status: 1 } },
      { fields: { validTill: 1 }, expireAfterSeconds: 0, partialFilterExpression: { status: 'USED' } },
    ],
    softDelete: false,
  }),

  /** Every physical gate crossing (visitor, delivery, cab, staff, vehicle) — §34, §43. */
  visitor_entries: defineCollection('visitor_entries', {
    entryType: S({
      enum: ['PRE_APPROVED', 'AT_GATE', 'DELIVERY', 'CAB', 'STAFF', 'VENDOR', 'EMERGENCY', 'VEHICLE'],
      required: true,
      index: true,
    }),
    direction: S({ enum: ['IN', 'OUT'], required: true, index: true }),
    visitorId: ref('visitors'),
    deliveryId: ref('deliveries'),
    cabEntryId: ref('cab_entries'),
    staffId: ref('staff'),
    vehicleId: ref('vehicles'),
    passId: ref('visitor_passes'),
    unitId: ref('units'),
    gateId: ref('gates', { required: true }),
    guardId: ref('users'),
    guardStaffId: ref('staff'),
    at: D({ required: true, index: true }),
    vehicleNumber: S(),
    photoUrl: S(),
    personName: S(),
    personPhone: S(),
    personCount: N({ default: 1 }),
    method: S({ enum: ['QR_SCAN', 'MANUAL', 'PRE_APPROVED', 'SYSTEM', 'RFID', 'ANPR'], default: 'MANUAL', index: true }),
    notes: S(),
    location: X(),
    clientRequestId: S({ index: true }),
    isOfflineCapture: B({ default: false }),
    syncedAt: D(),
  }, {
    indexes: [
      { fields: { societyId: 1, at: -1 } },
      { fields: { societyId: 1, gateId: 1, at: -1 } },
      { fields: { societyId: 1, unitId: 1, at: -1 } },
      { fields: { societyId: 1, entryType: 1, direction: 1, at: -1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
    ],
  }),

  deliveries: defineCollection('deliveries', {
    deliveryPersonName: S({ required: true, trim: true }),
    company: S({
      enum: ['AMAZON', 'FLIPKART', 'SWIGGY', 'ZOMATO', 'BLINKIT', 'ZEPTO', 'BIGBASKET', 'DUNZO', 'DELHIVERY', 'BLUEDART', 'DTDC', 'INDIA_POST', 'OTHER'],
      default: 'OTHER',
      index: true,
    }),
    companyName: S(),
    phone: S(),
    unitId: ref('units', { required: true }),
    residentId: ref('residents'),
    deliveryType: S({ enum: ['ECOMMERCE', 'FOOD', 'GROCERY', 'COURIER', 'PHARMACY', 'LAUNDRY', 'PACKAGE', 'OTHER'], default: 'PACKAGE', index: true }),
    orderId: S(),
    packageDescription: S(),
    vehicleNumber: S(),
    photoUrl: S(),
    gateId: ref('gates'),
    status: S({
      enum: ['AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'IGNORED', 'DELIVERED', 'INSIDE', 'EXITED', 'RETURNED', 'CANCELLED'],
      default: 'AWAITING_APPROVAL',
      index: true,
    }),
    requiresApproval: B({ default: false }),
    entryTime: D({ index: true }),
    exitTime: D(),
    deliveredAt: D(),
    decidedBy: ref('users'),
    decidedAt: D(),
    rejectReason: S(),
    recordedBy: ref('users'),
    notes: S(),
    timeline: A(),
    clientRequestId: S({ index: true }),
    isOfflineCapture: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, createdAt: -1 } },
      { fields: { societyId: 1, status: 1, createdAt: -1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
    ],
  }),

  cab_entries: defineCollection('cab_entries', {
    driverName: S({ required: true }),
    phone: S(),
    cabType: S({ enum: ['CAB', 'AUTO', 'TAXI', 'PRIVATE_DRIVER', 'PICKUP', 'DROP'], default: 'CAB', index: true }),
    provider: S({ enum: ['UBER', 'OLA', 'RAPIDO', 'MERU', 'PRIVATE', 'OTHER'], default: 'OTHER' }),
    vehicleNumber: S({ required: true, index: true }),
    unitId: ref('units', { required: true }),
    tripKind: S({ enum: ['PICKUP', 'DROP', 'BOTH'], default: 'BOTH' }),
    status: S({ enum: ['AWAITING_APPROVAL', 'APPROVED', 'REJECTED', 'INSIDE', 'EXITED', 'CANCELLED'], default: 'APPROVED', index: true }),
    accessId: ref('cab_access'),
    photoUrl: S(),
    gateId: ref('gates'),
    entryTime: D({ index: true }),
    exitTime: D(),
    recordedBy: ref('users'),
    notes: S(),
    clientRequestId: S({ index: true }),
    isOfflineCapture: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, createdAt: -1 } },
      { fields: { societyId: 1, vehicleNumber: 1, createdAt: -1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
    ],
  }),

  /** Resident-generated temporary cab access (§14). */
  cab_access: defineCollection('cab_access', {
    vehicleNumber: S({ required: true, index: true }),
    driverName: S(),
    driverPhone: S(),
    cabType: S({ default: 'CAB' }),
    unitId: ref('units', { required: true }),
    residentId: ref('residents'),
    passId: ref('visitor_passes'),
    validFrom: D({ required: true }),
    validTill: D({ required: true, index: true }),
    maxEntries: N({ default: 1 }),
    entriesUsed: N({ default: 0 }),
    purpose: S(),
    status: S({ enum: ['ACTIVE', 'USED', 'EXPIRED', 'REVOKED'], default: 'ACTIVE', index: true }),
  }, { indexes: [{ fields: { societyId: 1, vehicleNumber: 1, status: 1 } }, { fields: { societyId: 1, unitId: 1 } }] }),

  /* --------------------------------- staff -------------------------------- */

  staff: defineCollection('staff', {
    fullName: S({ required: true, trim: true }),
    phone: S({ required: true, index: true }),
    email: S({ lowercase: true }),
    photoUrl: S(),
    type: S({
      enum: ['MAID', 'COOK', 'DRIVER', 'BABYSITTER', 'GARDENER', 'CLEANER', 'TECHNICIAN', 'SECURITY', 'MAINTENANCE', 'HOUSEKEEPING', 'ELECTRICIAN', 'PLUMBER', 'RECEPTIONIST', 'MANAGER', 'OTHER'],
      required: true,
      index: true,
    }),
    employmentType: S({ enum: ['SOCIETY', 'PRIVATE', 'VENDOR', 'CONTRACT'], default: 'SOCIETY', index: true }),
    userId: ref('users'),
    address: X(),
    idProofType: S(),
    idProofNumber: S(),
    referenceDetails: S(),
    joiningDate: D(),
    exitDate: D(),
    monthlySalary: N(),
    workType: S({ enum: ['FULL_TIME', 'PART_TIME', 'DAILY', 'HOURLY', 'VISITING', 'CONTRACT'], default: 'FULL_TIME' }),
    workingDays: A({ default: () => [0, 1, 2, 3, 4, 5, 6] }),
    startTime: S(),
    endTime: S(),
    /** Units this staff member may visit — enforced at the gate (§15). */
    assignedUnitIds: A(),
    gateId: ref('gates'),
    shift: S({ enum: ['MORNING', 'AFTERNOON', 'NIGHT', 'GENERAL'] }),
    vendorId: ref('vendors'),
    qrPassId: ref('visitor_passes'),
    allowLogin: B({ default: false }),
    notifyResidentsOnArrival: B({ default: false }),
    status: S({ enum: ['ACTIVE', 'INACTIVE', 'SUSPENDED', 'TERMINATED'], default: 'ACTIVE', index: true }),
    policeVerificationStatus: S({ enum: ['PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'NOT_REQUIRED'], default: 'NOT_REQUIRED' }),
    rating: N(),
    lastEntryAt: D(),
  }, {
    indexes: [
      { fields: { societyId: 1, phone: 1 } },
      { fields: { societyId: 1, type: 1, status: 1 } },
      { fields: { societyId: 1, employmentType: 1 } },
    ],
  }),

  staff_attendance: defineCollection('staff_attendance', {
    staffId: ref('staff', { required: true }),
    userId: ref('users'),
    date: D({ required: true, index: true, description: 'Local calendar date' }),
    status: S({ enum: ['PRESENT', 'ABSENT', 'LATE', 'LEAVE', 'HALF_DAY'], required: true, index: true }),
    entryTime: D(),
    exitTime: D(),
    workedMinutes: N({ default: 0 }),
    gateId: ref('gates'),
    unitId: ref('units', { description: 'For private staff: which unit they visited' }),
    markedBy: ref('users'),
    markedAt: D(),
    method: S({ enum: ['MANUAL', 'QR_SCAN', 'BIOMETRIC', 'SELF', 'SYSTEM', 'OFFLINE_SYNC'], default: 'MANUAL' }),
    note: S(),
    photoUrl: S(),
    clientRequestId: S({ index: true }),
    isOfflineCapture: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, staffId: 1, date: 1 }, unique: true },
      { fields: { societyId: 1, date: 1, status: 1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
    ],
  }),

  /* -------------------------------- vendors ------------------------------- */

  vendors: defineCollection('vendors', {
    businessName: S({ required: true, trim: true }),
    contactPersonName: S(),
    phone: S({ required: true, index: true }),
    alternatePhone: S(),
    email: S({ lowercase: true }),
    userId: ref('users'),
    address: X(),
    gstin: S(),
    pan: S(),
    serviceCategories: A({ default: () => [] }),
    contractType: S({ enum: ['ONE_TIME', 'ANNUAL', 'MONTHLY', 'PER_VISIT', 'AMC'], default: 'PER_VISIT' }),
    contractValue: N(),
    agreementUrl: S(),
    startDate: D(),
    endDate: D(),
    bankAccountName: S(),
    bankAccountNumber: S({ description: 'Masked in every response' }),
    bankIfsc: S(),
    paymentTermsDays: N({ default: 15 }),
    rating: N({ default: 0 }),
    totalWorkOrders: N({ default: 0 }),
    completedWorkOrders: N({ default: 0 }),
    totalBilled: N({ default: 0 }),
    totalPaid: N({ default: 0 }),
    outstandingPayable: N({ default: 0 }),
    allowPortalLogin: B({ default: false }),
    status: S({ enum: ['ACTIVE', 'INACTIVE', 'BLACKLISTED', 'ON_HOLD'], default: 'ACTIVE', index: true }),
    documents: A(),
  }, { indexes: [{ fields: { societyId: 1, phone: 1 } }, { fields: { societyId: 1, status: 1 } }] }),

  /* ----------------------------- help desk ------------------------------- */

  complaints: defineCollection('complaints', {
    /** Human readable reference: `CMP-2026-000123`. */
    referenceNumber: S({ unique: true }),
    category: S({
      enum: ['PLUMBING', 'ELECTRICAL', 'LIFT', 'SECURITY', 'CLEANING', 'PARKING', 'WATER', 'GARBAGE', 'MAINTENANCE', 'COMMON_AREA', 'PEST_CONTROL', 'GARDEN', 'NOISE', 'NETWORK', 'OTHER'],
      required: true,
      index: true,
    }),
    title: S({ required: true, trim: true }),
    description: S({ required: true }),
    priority: S({ enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], default: 'MEDIUM', index: true }),
    status: S({
      enum: ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', 'REOPENED'],
      default: 'OPEN',
      index: true,
    }),
    source: S({ enum: ['RESIDENT', 'SECURITY', 'ADMIN', 'STAFF', 'SYSTEM'], default: 'RESIDENT', index: true }),
    locationType: S({ enum: ['UNIT', 'COMMON_AREA', 'BUILDING', 'AMENITY'], default: 'UNIT' }),
    unitId: ref('units'),
    residentId: ref('residents'),
    amenityId: ref('amenities'),
    locationText: S(),
    geo: X(),
    attachments: A(),
    assigneeType: S({ enum: ['STAFF', 'VENDOR', 'USER'] }),
    assigneeId: S({ index: true }),
    assigneeName: S(),
    workOrderId: ref('work_orders'),
    serviceRequestId: ref('service_requests'),
    /** SLA tracking (§19). */
    slaDueAt: D({ index: true }),
    slaBreached: B({ default: false, index: true }),
    firstResponseAt: D(),
    assignedAt: D(),
    startedAt: D(),
    resolvedAt: D(),
    closedAt: D(),
    rejectedAt: D(),
    reopenCount: N({ default: 0 }),
    resolutionSummary: S(),
    resolvedByName: S(),
    /** Resident verification + feedback (§54). */
    verifiedByResident: B({ default: false }),
    verifiedAt: D(),
    rating: N(),
    feedback: S(),
    qualityRating: N(),
    timelinessRating: N(),
    isAnonymous: B({ default: false }),
    isEscalated: B({ default: false }),
    escalationLevel: N({ default: 0 }),
    preferredContactTime: S(),
    timeline: A(),
    commentCount: N({ default: 0 }),
    charges: N({ default: 0 }),
    billableToResident: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, status: 1, createdAt: -1 } },
      { fields: { societyId: 1, unitId: 1, createdAt: -1 } },
      { fields: { societyId: 1, assigneeId: 1, status: 1 } },
      { fields: { societyId: 1, category: 1, status: 1 } },
      { fields: { societyId: 1, slaDueAt: 1 } },
      { fields: { referenceNumber: 1 }, unique: true, sparse: true },
    ],
  }),

  complaint_comments: defineCollection('complaint_comments', {
    complaintId: ref('complaints', { required: true }),
    authorId: ref('users'),
    authorName: S(),
    authorRole: S(),
    body: S({ required: true }),
    attachments: A(),
    /** `INTERNAL` comments are hidden from residents (§36 — no unnecessary exposure). */
    visibility: S({ enum: ['ALL', 'INTERNAL', 'RESIDENT'], default: 'ALL', index: true }),
    isSystem: B({ default: false }),
  }, { indexes: [{ fields: { societyId: 1, complaintId: 1, createdAt: 1 } }] }),

  service_requests: defineCollection('service_requests', {
    referenceNumber: S({ unique: true, sparse: true }),
    serviceType: S({
      enum: ['ELECTRICIAN', 'PLUMBER', 'CARPENTER', 'CLEANING', 'PEST_CONTROL', 'AC_SERVICE', 'APPLIANCE_REPAIR', 'PAINTING', 'MOVING', 'OTHER'],
      required: true,
      index: true,
    }),
    title: S({ required: true }),
    description: S(),
    unitId: ref('units', { required: true }),
    residentId: ref('residents'),
    status: S({
      enum: ['PENDING', 'ASSIGNED', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'CLOSED'],
      default: 'PENDING',
      index: true,
    }),
    preferredDate: D({ index: true }),
    preferredSlot: S({ enum: ['MORNING', 'AFTERNOON', 'EVENING', 'ANY'], default: 'ANY' }),
    preferredTimeFrom: S(),
    preferredTimeTo: S(),
    scheduledAt: D(),
    completedAt: D(),
    vendorId: ref('vendors'),
    vendorName: S(),
    assignedStaffId: ref('staff'),
    workOrderId: ref('work_orders'),
    estimatedCharges: N(),
    actualCharges: N(),
    isBillable: B({ default: true }),
    billId: ref('maintenance_bills'),
    attachments: A(),
    addressNote: S(),
    rating: N(),
    feedback: S(),
    timeline: A(),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, createdAt: -1 } },
      { fields: { societyId: 1, status: 1, preferredDate: 1 } },
    ],
  }),

  work_orders: defineCollection('work_orders', {
    referenceNumber: S({ unique: true, sparse: true }),
    title: S({ required: true }),
    description: S(),
    complaintId: ref('complaints'),
    serviceRequestId: ref('service_requests'),
    category: S(),
    priority: S({ enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], default: 'MEDIUM', index: true }),
    status: S({
      enum: ['REQUESTED', 'CREATED', 'ASSIGNED', 'STARTED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CLOSED', 'CANCELLED', 'ON_HOLD'],
      default: 'CREATED',
      index: true,
    }),
    assigneeType: S({ enum: ['STAFF', 'VENDOR', 'USER'] }),
    assigneeId: S({ index: true }),
    assigneeName: S(),
    vendorId: ref('vendors'),
    buildingId: ref('buildings'),
    unitId: ref('units'),
    amenityId: ref('amenities'),
    scheduledStart: D(),
    scheduledEnd: D(),
    startedAt: D(),
    completedAt: D(),
    verifiedAt: D(),
    closedAt: D(),
    estimatedCost: N(),
    actualCost: N(),
    materialCost: N({ default: 0 }),
    labourCost: N({ default: 0 }),
    materialRequired: S(),
    progressPercent: N({ default: 0 }),
    billId: ref('maintenance_bills'),
    expenseId: ref('expenses'),
    rating: N(),
    feedback: S(),
    /** Full state history (§31 "maintain complete history"). */
    history: A(),
    attachments: A(),
  }, {
    indexes: [
      { fields: { societyId: 1, status: 1, createdAt: -1 } },
      { fields: { societyId: 1, assigneeId: 1, status: 1 } },
      { fields: { societyId: 1, vendorId: 1, status: 1 } },
    ],
  }),

  /* ------------------------------- amenities ------------------------------ */

  amenities: defineCollection('amenities', {
    name: S({ required: true, trim: true }),
    type: S({
      enum: ['CLUBHOUSE', 'SWIMMING_POOL', 'GYM', 'PARTY_HALL', 'GARDEN', 'SPORTS_COURT', 'COMMUNITY_HALL', 'MEETING_ROOM', 'LIBRARY', 'INDOOR_GAMES', 'YOGA_DECK', 'PLAYGROUND', 'BBQ_AREA', 'AMPHITHEATRE', 'OTHER'],
      default: 'OTHER',
      index: true,
    }),
    description: S(),
    rules: A(),
    capacity: N({ default: 1 }),
    openTime: S({ default: '06:00' }),
    closeTime: S({ default: '22:00' }),
    slotDurationMinutes: N({ default: 60 }),
    slotGapMinutes: N({ default: 0 }),
    bookingFee: N({ default: 0 }),
    deposit: N({ default: 0 }),
    requireApproval: B({ default: false }),
    allowCancellation: B({ default: true }),
    cancellationHoursBefore: N({ default: 24 }),
    refundPercent: N({ default: 100 }),
    maxAdvanceDays: N({ default: 30 }),
    maxSlotsPerUserPerDay: N({ default: 2 }),
    closedOnDays: A(),
    photoUrl: S(),
    buildingId: ref('buildings'),
    location: X(),
    isActive: B({ default: true, index: true }),
    totalBookings: N({ default: 0 }),
    totalRevenue: N({ default: 0 }),
  }, { indexes: [{ fields: { societyId: 1, isActive: 1 } }, { fields: { societyId: 1, name: 1 } }] }),

  /** Recurring availability windows; bookings reference the slot they consumed. */
  amenity_slots: defineCollection('amenity_slots', {
    amenityId: ref('amenities', { required: true }),
    dayOfWeek: N({ description: '0=Sunday … 6=Saturday; null = every day' }),
    startTime: S({ required: true }),
    endTime: S({ required: true }),
    capacity: N({ default: 1 }),
    fee: N({ default: 0 }),
    isBlocked: B({ default: false }),
    validFrom: D(),
    validTill: D(),
    isActive: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, amenityId: 1, isActive: 1 } }] }),

  amenity_bookings: defineCollection('amenity_bookings', {
    referenceNumber: S({ unique: true, sparse: true }),
    amenityId: ref('amenities', { required: true }),
    slotId: ref('amenity_slots'),
    unitId: ref('units', { required: true }),
    residentId: ref('residents'),
    userId: ref('users'),
    date: D({ required: true, index: true }),
    startTime: S({ required: true }),
    endTime: S({ required: true }),
    /** Materialised window used for overlap (double-booking) detection. */
    windowStart: D({ required: true, index: true }),
    windowEnd: D({ required: true, index: true }),
    numberOfPeople: N({ default: 1 }),
    status: S({
      enum: ['PENDING_APPROVAL', 'PENDING_PAYMENT', 'CONFIRMED', 'CANCELLED', 'REJECTED', 'COMPLETED', 'NO_SHOW', 'REFUNDED'],
      default: 'PENDING_APPROVAL',
      index: true,
    }),
    fee: N({ default: 0 }),
    deposit: N({ default: 0 }),
    totalAmount: N({ default: 0 }),
    paymentId: ref('payments'),
    isPaid: B({ default: false }),
    passId: ref('visitor_passes', { description: 'Booking QR (§57)' }),
    purpose: S(),
    notes: S(),
    approvedBy: ref('users'),
    decidedAt: D(),
    rejectReason: S(),
    cancelledAt: D(),
    cancellationReason: S(),
    refundAmount: N({ default: 0 }),
    checkedInAt: D(),
    checkedOutAt: D(),
    clientRequestId: S({ index: true }),
  }, {
    indexes: [
      // Double-booking guard (§22): the amenity-booking service queries this index for
      // overlapping windows before inserting, inside a transaction.
      { fields: { societyId: 1, amenityId: 1, windowStart: 1, windowEnd: 1, status: 1 } },
      { fields: { societyId: 1, unitId: 1, date: -1 } },
      { fields: { societyId: 1, status: 1, date: 1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
    ],
  }),

  /* ------------------------------ community ------------------------------ */

  notices: defineCollection('notices', {
    title: S({ required: true, trim: true }),
    body: S({ required: true }),
    type: S({
      enum: ['GENERAL', 'MAINTENANCE', 'EMERGENCY', 'EVENT', 'WATER_SHUTDOWN', 'ELECTRICITY_SHUTDOWN', 'SECURITY_ALERT', 'MEETING', 'IMPORTANT', 'RULES', 'FINANCIAL'],
      default: 'GENERAL',
      index: true,
    }),
    kind: S({ enum: ['NOTICE', 'ANNOUNCEMENT', 'UPDATE', 'ALERT', 'REMINDER'], default: 'NOTICE', index: true }),
    status: S({ enum: ['DRAFT', 'PUBLISHED', 'ARCHIVED'], default: 'DRAFT', index: true }),
    /** Targeting (§24): society / building / wing / floor / unit / role. */
    audienceType: S({ enum: ['ALL', 'BUILDING', 'WING', 'FLOOR', 'UNIT', 'ROLE', 'OWNERS_ONLY', 'TENANTS_ONLY', 'STAFF', 'COMMITTEE'], default: 'ALL', index: true }),
    audienceIds: A(),
    audienceRoles: A(),
    attachments: A(),
    publishedAt: D({ index: true }),
    publishAt: D(),
    expiresAt: D(),
    isPinned: B({ default: false }),
    requireAcknowledgement: B({ default: false }),
    acknowledgeBy: D(),
    viewCount: N({ default: 0 }),
    acknowledgementCount: N({ default: 0 }),
    audienceCount: N({ default: 0 }),
    channelsUsed: A(),
  }, {
    indexes: [
      { fields: { societyId: 1, status: 1, publishedAt: -1 } },
      { fields: { societyId: 1, type: 1, publishedAt: -1 } },
    ],
  }),

  events: defineCollection('events', {
    name: S({ required: true, trim: true }),
    description: S(),
    startDate: D({ required: true, index: true }),
    endDate: D({ required: true }),
    location: S(),
    amenityId: ref('amenities'),
    bannerUrl: S(),
    capacity: N({ default: 0 }),
    registeredCount: N({ default: 0 }),
    attendingCount: N({ default: 0 }),
    requiresRegistration: B({ default: true }),
    fee: N({ default: 0 }),
    collectedAmount: N({ default: 0 }),
    allowGuests: B({ default: true }),
    maxGuestsPerRegistration: N({ default: 4 }),
    registrationDeadline: D(),
    audienceType: S({ default: 'ALL' }),
    audienceIds: A(),
    status: S({ enum: ['DRAFT', 'PUBLISHED', 'ONGOING', 'COMPLETED', 'CANCELLED'], default: 'DRAFT', index: true }),
    organiserId: ref('users'),
    organiserName: S(),
  }, { indexes: [{ fields: { societyId: 1, status: 1, startDate: 1 } }] }),

  event_registrations: defineCollection('event_registrations', {
    eventId: ref('events', { required: true }),
    unitId: ref('units'),
    residentId: ref('residents'),
    userId: ref('users'),
    status: S({ enum: ['ATTENDING', 'NOT_ATTENDING', 'MAYBE'], required: true, index: true }),
    guests: N({ default: 0 }),
    note: S(),
    paymentId: ref('payments'),
    amountPaid: N({ default: 0 }),
    passId: ref('visitor_passes'),
    checkedInAt: D(),
    clientRequestId: S({ index: true }),
  }, {
    indexes: [
      { fields: { societyId: 1, eventId: 1, unitId: 1 }, unique: true },
      { fields: { societyId: 1, eventId: 1, status: 1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
    ],
  }),

  polls: defineCollection('polls', {
    question: S({ required: true }),
    description: S(),
    status: S({ enum: ['DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED'], default: 'DRAFT', index: true }),
    allowMultipleChoice: B({ default: false }),
    isAnonymous: B({ default: false }),
    startDate: D({ required: true }),
    endDate: D({ required: true, index: true }),
    eligibleAudience: S({ default: 'ALL' }),
    eligibleAudienceIds: A(),
    eligibleRoles: A(),
    oneVotePerUnit: B({ default: true }),
    showResultsBeforeClose: B({ default: false }),
    totalVotes: N({ default: 0 }),
    eligibleVoters: N({ default: 0 }),
    publishedAt: D(),
    closedAt: D(),
    createdByUserId: ref('users'),
  }, { indexes: [{ fields: { societyId: 1, status: 1, endDate: 1 } }] }),

  poll_options: defineCollection('poll_options', {
    pollId: ref('polls', { required: true }),
    label: S({ required: true }),
    value: S(),
    order: N({ default: 0 }),
    voteCount: N({ default: 0 }),
    isActive: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, pollId: 1, order: 1 } }] }),

  poll_votes: defineCollection('poll_votes', {
    pollId: ref('polls', { required: true }),
    optionIds: A({ required: true }),
    /** Stored for duplicate prevention; omitted from results when `poll.isAnonymous`. */
    userId: ref('users'),
    residentId: ref('residents'),
    unitId: ref('units'),
    isAnonymous: B({ default: false }),
    /** Hash of (pollId|unitId) used as the uniqueness key for anonymous polls. */
    anonymousKey: S({ index: true }),
    ip: S(),
    deviceId: S(),
    votedAt: D({ required: true }),
  }, {
    indexes: [
      { fields: { societyId: 1, pollId: 1, unitId: 1 }, unique: true, sparse: true },
      { fields: { societyId: 1, pollId: 1, anonymousKey: 1 }, unique: true, sparse: true },
      { fields: { societyId: 1, pollId: 1 } },
    ],
    description: 'Audit record for every vote; identity is withheld from results when anonymous.',
  }),

  /* -------------------------------- finance ------------------------------ */

  maintenance_bills: defineCollection('maintenance_bills', {
    /** `INV-2026-000123` (§59 tax invoice / receipt numbering). */
    invoiceNumber: S({ unique: true }),
    unitId: ref('units', { required: true }),
    residentId: ref('residents', { description: 'Billable member (owner for owners, tenant when agreed)' }),
    period: S({ required: true, index: true, description: 'YYYY-MM' }),
    periodStart: D({ required: true }),
    periodEnd: D({ required: true }),
    generatedAt: D(),
    dueDate: D({ required: true, index: true }),
    status: S({
      enum: ['DRAFT', 'GENERATED', 'SENT', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'WAIVED', 'CANCELLED', 'DISPUTED'],
      default: 'GENERATED',
      index: true,
    }),
    subtotal: N({ default: 0 }),
    discount: N({ default: 0 }),
    discountReason: S(),
    taxBreakup: X({ default: () => ({ cgst: 0, sgst: 0, igst: 0, cess: 0, taxableAmount: 0 }) }),
    totalTax: N({ default: 0 }),
    arrears: N({ default: 0 }),
    penalty: N({ default: 0 }),
    lateFee: N({ default: 0 }),
    totalAmount: N({ required: true, default: 0 }),
    paidAmount: N({ default: 0 }),
    dueAmount: N({ default: 0, index: true }),
    waivedAmount: N({ default: 0 }),
    refundedAmount: N({ default: 0 }),
    currency: S({ default: 'INR' }),
    notes: S(),
    /** Bill lines live in `bill_items`; kept normalised per §53. */
    itemCount: N({ default: 0 }),
    paymentIds: A(),
    lastPaymentAt: D(),
    paidAt: D(),
    sentAt: D(),
    reminderCount: N({ default: 0 }),
    lastReminderAt: D(),
    overdueSince: D(),
    pdfUrl: S(),
    generationMode: S({ enum: ['MANUAL', 'BULK', 'SCHEDULED'], default: 'MANUAL', index: true }),
    disputedReason: S(),
    /** Snapshot of the rates used, so later config changes never rewrite history. */
    configSnapshot: X(),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, period: 1 }, unique: true },
      { fields: { societyId: 1, status: 1, dueDate: 1 } },
      { fields: { societyId: 1, period: 1, status: 1 } },
      { fields: { invoiceNumber: 1 }, unique: true, sparse: true },
    ],
    description: 'One bill per unit per period (unique) — makes duplicate generation impossible.',
  }),

  bill_items: defineCollection('bill_items', {
    billId: ref('maintenance_bills', { required: true }),
    type: S({
      enum: ['MAINTENANCE', 'FIXED_CHARGE', 'VARIABLE_CHARGE', 'WATER', 'PARKING', 'CLUBHOUSE', 'SINKING_FUND', 'REPAIR_FUND', 'PENALTY', 'LATE_FEE', 'SERVICE_CHARGE', 'EVENT_FEE', 'AMENITY_FEE', 'ARREARS', 'OTHER'],
      required: true,
      index: true,
    }),
    label: S({ required: true }),
    amount: N({ required: true }),
    quantity: N({ default: 1 }),
    rate: N(),
    isTaxable: B({ default: false }),
    taxPercent: N({ default: 0 }),
    taxType: S({ enum: ['CGST', 'SGST', 'IGST', 'CESS', 'NONE'], default: 'NONE' }),
    taxAmount: N({ default: 0 }),
    order: N({ default: 0 }),
    ledgerId: ref('ledgers'),
    meta: X(),
  }, { indexes: [{ fields: { societyId: 1, billId: 1, order: 1 } }, { fields: { societyId: 1, type: 1 } }] }),

  /** A logical payment (one per user action). Gateway attempts live in payment_transactions. */
  payments: defineCollection('payments', {
    referenceNumber: S({ unique: true, sparse: true }),
    unitId: ref('units'),
    residentId: ref('residents'),
    userId: ref('users'),
    purpose: S({
      enum: ['MAINTENANCE', 'AMENITY_BOOKING', 'PARKING', 'SERVICE_CHARGE', 'EVENT_FEE', 'FINE', 'DONATION', 'SUBSCRIPTION', 'OTHER'],
      required: true,
      index: true,
    }),
    status: S({
      enum: ['INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'CANCELLED', 'ABANDONED'],
      default: 'INITIATED',
      index: true,
    }),
    amount: N({ required: true }),
    currency: S({ default: 'INR' }),
    paidAmount: N({ default: 0 }),
    refundedAmount: N({ default: 0 }),
    mode: S({ enum: ['ONLINE', 'UPI', 'CARD', 'NETBANKING', 'CASH', 'CHEQUE', 'DD', 'BANK_TRANSFER', 'WALLET'] }),
    provider: S({ index: true }),
    providerOrderId: S({ index: true }),
    providerPaymentId: S({ index: true }),
    /** Linked documents. */
    billId: ref('maintenance_bills'),
    bookingId: ref('amenity_bookings'),
    eventId: ref('events'),
    serviceRequestId: ref('service_requests'),
    expenseId: ref('expenses'),
    ledgerId: ref('ledgers'),
    journalEntryId: ref('journal_entries'),
    receiptNumber: S({ unique: true, sparse: true }),
    receiptUrl: S(),
    receiptGeneratedAt: D(),
    initiatedAt: D(),
    paidAt: D({ index: true }),
    failedAt: D(),
    refundedAt: D(),
    referenceNote: S(),
    failureReason: S(),
    gatewayMessage: S(),
    signatureVerified: B({ default: false }),
    isOffline: B({ default: false }),
    collectedBy: ref('users'),
    clientRequestId: S({ index: true }),
    /** Immutable trail of every gateway interaction. */
    transactions: A(),
    webhookReceivedAt: D(),
    metadata: X(),
  }, {
    indexes: [
      { fields: { societyId: 1, unitId: 1, createdAt: -1 } },
      { fields: { societyId: 1, status: 1, paidAt: -1 } },
      { fields: { societyId: 1, billId: 1 } },
      { fields: { societyId: 1, providerOrderId: 1 } },
      { fields: { societyId: 1, clientRequestId: 1 }, unique: true, sparse: true },
      { fields: { receiptNumber: 1 }, unique: true, sparse: true },
    ],
  }),

  payment_transactions: defineCollection('payment_transactions', {
    paymentId: ref('payments', { required: true }),
    provider: S({ required: true }),
    providerOrderId: S({ index: true }),
    providerPaymentId: S({ index: true }),
    providerSignature: S(),
    type: S({ enum: ['ORDER_CREATED', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', 'WEBHOOK', 'VERIFICATION'], required: true, index: true }),
    status: S({ enum: ['INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'REFUNDED'], default: 'INITIATED' }),
    amount: N({ required: true }),
    currency: S({ default: 'INR' }),
    fee: N({ default: 0 }),
    rawRequest: X(),
    rawResponse: X(),
    errorCode: S(),
    errorMessage: S(),
    idempotencyKey: S({ index: true }),
    clientIp: S(),
    occurredAt: D({ index: true }),
  }, {
    indexes: [
      { fields: { societyId: 1, paymentId: 1, occurredAt: 1 } },
      { fields: { societyId: 1, providerPaymentId: 1 } },
    ],
    softDelete: false,
  }),

  ledgers: defineCollection('ledgers', {
    name: S({ required: true }),
    code: S({ index: true }),
    type: S({
      enum: ['MAINTENANCE_INCOME', 'WATER_INCOME', 'PARKING_INCOME', 'AMENITY_INCOME', 'EVENT_INCOME', 'INTEREST_INCOME', 'OTHER_INCOME', 'VENDOR_EXPENSE', 'ELECTRICITY_EXPENSE', 'SECURITY_EXPENSE', 'HOUSEKEEPING_EXPENSE', 'REPAIR_EXPENSE', 'ADMINISTRATIVE_EXPENSE', 'SALARY_EXPENSE', 'OTHER_EXPENSE', 'ASSET', 'LIABILITY'],
      required: true,
      index: true,
    }),
    group: S({ enum: ['INCOME', 'EXPENSE', 'ASSET', 'LIABILITY', 'EQUITY'], required: true, index: true }),
    openingBalance: N({ default: 0 }),
    currentBalance: N({ default: 0 }),
    isSystem: B({ default: false }),
    vendorId: ref('vendors'),
    unitId: ref('units'),
    description: S(),
    isActive: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, name: 1 }, unique: true }, { fields: { societyId: 1, group: 1 } }] }),

  /** Double-entry journal (§29). A posted entry is immutable; corrections are new entries. */
  journal_entries: defineCollection('journal_entries', {
    entryNumber: S({ unique: true, sparse: true }),
    date: D({ required: true, index: true }),
    narration: S({ required: true }),
    referenceType: S({ enum: ['PAYMENT', 'RECEIPT', 'EXPENSE', 'INCOME', 'BILL', 'ADJUSTMENT', 'OPENING'], default: 'ADJUSTMENT', index: true }),
    referenceId: S({ index: true }),
    totalDebit: N({ required: true, default: 0 }),
    totalCredit: N({ required: true, default: 0 }),
    lines: A({ required: true, description: '[{ ledgerId, type: DEBIT|CREDIT, amount, note }]' }),
    isPosted: B({ default: true }),
    postedAt: D(),
    reversedByEntryId: ref('journal_entries'),
    reversesEntryId: ref('journal_entries'),
    unitId: ref('units'),
    vendorId: ref('vendors'),
    paymentId: ref('payments'),
    attachments: A(),
  }, {
    indexes: [
      { fields: { societyId: 1, date: -1 } },
      { fields: { societyId: 1, referenceType: 1, referenceId: 1 } },
      { fields: { entryNumber: 1 }, unique: true, sparse: true },
    ],
    description: 'Debits must equal credits; validated inside a transaction before insert.',
  }),

  expenses: defineCollection('expenses', {
    title: S({ required: true }),
    ledgerId: ref('ledgers', { required: true }),
    vendorId: ref('vendors'),
    workOrderId: ref('work_orders'),
    amount: N({ required: true }),
    date: D({ required: true, index: true }),
    category: S(),
    gstin: S(),
    taxableAmount: N(),
    cgst: N({ default: 0 }),
    sgst: N({ default: 0 }),
    igst: N({ default: 0 }),
    invoiceNumber: S(),
    paymentMode: S(),
    attachments: A(),
    note: S(),
    isPaid: B({ default: false, index: true }),
    paidAt: D(),
    paymentId: ref('payments'),
    journalEntryId: ref('journal_entries'),
    approvedBy: ref('users'),
    approvedAt: D(),
    status: S({ enum: ['DRAFT', 'SUBMITTED', 'APPROVED', 'PAID', 'REJECTED'], default: 'SUBMITTED', index: true }),
  }, { indexes: [{ fields: { societyId: 1, date: -1 } }, { fields: { societyId: 1, vendorId: 1, isPaid: 1 } }] }),

  incomes: defineCollection('incomes', {
    title: S({ required: true }),
    ledgerId: ref('ledgers', { required: true }),
    unitId: ref('units'),
    source: S(),
    amount: N({ required: true }),
    date: D({ required: true, index: true }),
    paymentId: ref('payments'),
    journalEntryId: ref('journal_entries'),
    gstin: S(),
    taxableAmount: N(),
    cgst: N({ default: 0 }),
    sgst: N({ default: 0 }),
    igst: N({ default: 0 }),
    invoiceNumber: S(),
    attachments: A(),
    note: S(),
    isReceived: B({ default: true }),
  }, { indexes: [{ fields: { societyId: 1, date: -1 } }, { fields: { societyId: 1, ledgerId: 1 } }] }),

  /** Per-society subscription mirror so tenant APIs can gate modules without a cross-DB read. */
  subscriptions: defineCollection('subscriptions', {
    planId: S({ required: true }),
    planCode: S({ required: true, index: true }),
    tier: S({ index: true }),
    status: S({ enum: ['TRIAL', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', 'SUSPENDED'], default: 'TRIAL', index: true }),
    startDate: D({ required: true }),
    endDate: D({ required: true, index: true }),
    billingCycle: S({ default: 'MONTHLY' }),
    /** Enabled ModuleKey values — the authoritative list for `requireModule`. */
    modules: A({ default: () => [] }),
    limits: X({ default: () => ({}) }),
    autoRenew: B({ default: true }),
    syncedFromPlatformAt: D(),
  }, { indexes: [{ fields: { societyId: 1, status: 1 } }] }),

  /* ------------------------------ documents ------------------------------ */

  documents: defineCollection('documents', {
    title: S({ required: true }),
    category: S({
      enum: ['REGISTRATION', 'BYE_LAWS', 'RULES', 'MEETING_MINUTES', 'NOTICE', 'BILL', 'RECEIPT', 'VENDOR_AGREEMENT', 'CERTIFICATE', 'AUDIT_REPORT', 'INSURANCE', 'ID_PROOF', 'OWNERSHIP_PROOF', 'RENT_AGREEMENT', 'PHOTO', 'OTHER'],
      default: 'OTHER',
      index: true,
    }),
    /** Access is checked server-side against this visibility (§37). */
    visibility: S({ enum: ['PUBLIC', 'RESIDENTS', 'OWNERS_ONLY', 'COMMITTEE', 'STAFF', 'PRIVATE'], default: 'RESIDENTS', index: true }),
    description: S(),
    fileName: S({ required: true }),
    mimeType: S({ required: true }),
    sizeBytes: N({ required: true, default: 0 }),
    /** Storage key (never a public URL for private docs) + provider. */
    storageKey: S({ required: true }),
    storageProvider: S({ default: 'local' }),
    checksum: S({ description: 'SHA-256 of the bytes — detects tampering' }),
    unitId: ref('units'),
    residentId: ref('residents'),
    buildingId: ref('buildings'),
    vendorId: ref('vendors'),
    billId: ref('maintenance_bills'),
    complaintId: ref('complaints'),
    requireAcknowledgement: B({ default: false }),
    acknowledgeBy: D(),
    acknowledgementCount: N({ default: 0 }),
    tags: A(),
    validTill: D(),
    downloadCount: N({ default: 0 }),
    uploadedBy: ref('users'),
    uploadedByName: S(),
    /** Short-lived signed access is minted per request; the document itself stays private. */
    isPublicUrl: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, category: 1, createdAt: -1 } },
      { fields: { societyId: 1, visibility: 1 } },
      { fields: { societyId: 1, unitId: 1 } },
    ],
  }),

  document_acknowledgements: defineCollection('document_acknowledgements', {
    documentId: ref('documents', { required: true }),
    userId: ref('users', { required: true }),
    residentId: ref('residents'),
    unitId: ref('units'),
    acknowledgedAt: D({ required: true }),
    viewedSeconds: N({ default: 0 }),
    note: S(),
    /** Captured where legally appropriate (§38). */
    ip: S(),
    userAgent: S(),
    deviceId: S(),
    platform: S(),
  }, {
    indexes: [{ fields: { societyId: 1, documentId: 1, userId: 1 }, unique: true }],
    description: 'One acknowledgement per user per document (unique) — cannot be forged twice.',
  }),

  /* ---------------------------- notifications ---------------------------- */

  notifications: defineCollection('notifications', {
    userId: ref('users', { required: true, index: true }),
    residentId: ref('residents'),
    unitId: ref('units'),
    type: S({ required: true, index: true, description: 'NotificationEvent key' }),
    title: S({ required: true }),
    message: S({ required: true }),
    body: S(),
    data: X({ default: () => ({}) }),
    deepLink: S(),
    priority: S({ enum: ['LOW', 'NORMAL', 'HIGH', 'CRITICAL'], default: 'NORMAL' }),
    channels: A({ default: () => ['IN_APP'] }),
    status: S({ enum: ['QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'READ', 'SKIPPED'], default: 'QUEUED', index: true }),
    readAt: D(),
    sentAt: D(),
    deliveredAt: D(),
    failedAt: D(),
    failureReason: S(),
    /** Delivery outcome per channel, kept for auditing the notification engine. */
    deliveries: A(),
    actionLabel: S(),
    actionUrl: S(),
    groupId: S({ index: true, description: 'Collapse related notifications' }),
    isCritical: B({ default: false }),
    expiresAt: D(),
  }, {
    indexes: [
      { fields: { societyId: 1, userId: 1, readAt: 1, createdAt: -1 } },
      { fields: { societyId: 1, type: 1, createdAt: -1 } },
      { fields: { societyId: 1, status: 1, createdAt: -1 } },
    ],
  }),

  /** Per-society template overrides of the platform notification templates (§55). */
  notification_templates: defineCollection('notification_templates', {
    code: S({ required: true }),
    title: S({ required: true }),
    body: S({ required: true }),
    channels: A({ default: () => ['IN_APP'] }),
    priority: S({ default: 'NORMAL' }),
    variables: A(),
    deepLinkTemplate: S(),
    isActive: B({ default: true }),
    locale: S({ default: 'en-IN' }),
  }, { indexes: [{ fields: { societyId: 1, code: 1 }, unique: true }] }),

  /** Push tokens per device (FCM / Expo). */
  push_tokens: defineCollection('push_tokens', {
    userId: ref('users', { required: true }),
    sessionId: ref('sessions'),
    token: S({ required: true, index: true }),
    provider: S({ enum: ['FCM', 'EXPO', 'APNS'], default: 'FCM' }),
    platform: S({ enum: ['ios', 'android', 'web'], default: 'android' }),
    deviceId: S(),
    appVersion: S(),
    isActive: B({ default: true }),
    lastUsedAt: D(),
    failureCount: N({ default: 0 }),
  }, { indexes: [{ fields: { societyId: 1, userId: 1, isActive: 1 } }, { fields: { token: 1 }, unique: true }] }),

  /* ------------------------------ emergency ------------------------------ */

  emergency_alerts: defineCollection('emergency_alerts', {
    category: S({
      enum: ['MEDICAL', 'FIRE', 'SECURITY', 'ACCIDENT', 'GAS_LEAK', 'WATER_LEAKAGE', 'ELECTRIC_SHOCK', 'LIFT_STUCK', 'THEFT', 'OTHER'],
      required: true,
      index: true,
    }),
    severity: S({ enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'], default: 'HIGH', index: true }),
    status: S({ enum: ['ACTIVE', 'ACKNOWLEDGED', 'RESPONDING', 'RESOLVED', 'FALSE_ALARM'], default: 'ACTIVE', index: true }),
    unitId: ref('units'),
    buildingId: ref('buildings'),
    residentId: ref('residents'),
    raisedByUserId: ref('users'),
    raisedByName: S(),
    contactPhone: S(),
    location: S(),
    geo: X(),
    description: S(),
    photoUrls: A(),
    raisedAt: D({ required: true, index: true }),
    acknowledgedAt: D(),
    acknowledgedBy: ref('users'),
    resolvedAt: D(),
    resolvedBy: ref('users'),
    resolutionNote: S(),
    notifiedUserIds: A(),
    notifiedContacts: A(),
    gateId: ref('gates'),
    timeline: A(),
    /** False alarms are tracked so repeat offenders can be counselled. */
    isFalseAlarm: B({ default: false }),
  }, {
    indexes: [
      { fields: { societyId: 1, status: 1, raisedAt: -1 } },
      { fields: { societyId: 1, unitId: 1, raisedAt: -1 } },
    ],
  }),

  /* -------------------------------- audit -------------------------------- */

  audit_logs: defineCollection('audit_logs', {
    actorId: S({ index: true }),
    actorType: S({ enum: ['USER', 'SYSTEM', 'JOB', 'PLATFORM'], default: 'USER' }),
    actorName: S(),
    actorRoles: A(),
    actorUnitId: ref('units'),
    action: S({ required: true, index: true }),
    module: S({ required: true, index: true }),
    recordId: S({ index: true }),
    recordType: S(),
    oldValue: X(),
    newValue: X(),
    changedFields: A(),
    ip: S(),
    userAgent: S(),
    deviceId: S(),
    platform: S(),
    requestId: S({ index: true }),
    gateId: ref('gates'),
    severity: S({ enum: ['INFO', 'NOTICE', 'WARNING', 'CRITICAL'], default: 'INFO' }),
    status: S({ enum: ['SUCCESS', 'FAILURE'], default: 'SUCCESS' }),
    errorMessage: S(),
    tookMs: N(),
    meta: X({ description: 'Free-form extra detail (e.g. the reason a login failed)' }),
  }, {
    softDelete: false,
    indexes: [
      { fields: { societyId: 1, createdAt: -1 } },
      { fields: { societyId: 1, module: 1, action: 1, createdAt: -1 } },
      { fields: { societyId: 1, actorId: 1, createdAt: -1 } },
      { fields: { societyId: 1, recordId: 1 } },
    ],
    description: 'Append-only; no update/delete endpoint exists (§44).',
  }),

  /* ------------------------------ infrastructure -------------------------- */

  /** Idempotency keys per tenant — protects offline sync and payment retries (§50, §77). */
  idempotency_keys: defineCollection('idempotency_keys', {
    key: S({ required: true }),
    userId: S(),
    method: S(),
    path: S(),
    requestHash: S(),
    status: S({ enum: ['PROCESSING', 'COMPLETED', 'FAILED'], default: 'PROCESSING' }),
    responseStatus: N(),
    responseBody: X(),
    recordId: S(),
    collectionName: S(),
    expiresAt: D({ required: true }),
  }, {
    softDelete: false,
    indexes: [{ fields: { societyId: 1, key: 1 }, unique: true }, { fields: { expiresAt: 1 }, expireAfterSeconds: 0 }],
  }),

  /** Monotonic counters for human-readable references (invoice/receipt/complaint numbers). */
  counters: defineCollection('counters', {
    key: S({ required: true }),
    seq: N({ required: true, default: 0 }),
    year: N(),
    updatedAt: D(),
  }, {
    softDelete: false,
    timestamps: false,
    indexes: [{ fields: { societyId: 1, key: 1 }, unique: true }],
  }),

  /** Tenant background jobs (§61). Platform-wide jobs live in the platform DB. */
  jobs: defineCollection('jobs', {
    name: S({ required: true, index: true }),
    queue: S({ default: 'default', index: true }),
    payload: X({ default: () => ({}) }),
    status: S({ enum: ['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED'], default: 'QUEUED', index: true }),
    priority: N({ default: 0 }),
    attempts: N({ default: 0 }),
    maxAttempts: N({ default: 3 }),
    scheduledFor: D({ index: true }),
    startedAt: D(),
    completedAt: D(),
    lastError: S(),
    result: X(),
    idempotencyKey: S({ index: true }),
  }, { softDelete: false, indexes: [{ fields: { societyId: 1, status: 1, scheduledFor: 1 } }, { fields: { societyId: 1, idempotencyKey: 1 }, unique: true, sparse: true }] }),

  /**
   * One row per (job, local calendar day) proving the day's scheduled maintenance already ran.
   *
   * The unique index is the point: claiming a day is an upsert, so when several API replicas tick
   * at the same moment only one wins the insert and the rest see the row already there. Without
   * this, late fees would be applied once per replica — a real money bug, not a cosmetic one.
   * Keyed on the *society's* local date, not UTC, so a 2am run means 2am where the society is.
   */
  scheduler_runs: defineCollection('scheduler_runs', {
    job: S({ required: true }),
    /** Local calendar day for the society's timezone, `YYYY-MM-DD`. */
    dateKey: S({ required: true }),
    timezone: S(),
    status: S({ enum: ['RUNNING', 'COMPLETED', 'FAILED'], default: 'RUNNING' }),
    startedAt: D(),
    finishedAt: D(),
    result: X(),
    lastError: S(),
  }, {
    softDelete: false,
    timestamps: false,
    indexes: [{ fields: { societyId: 1, job: 1, dateKey: 1 }, unique: true }],
  }),

  /** Optional community chat (§36). Threads are scoped to a unit/complaint, never global. */
  conversations: defineCollection('conversations', {
    subject: S({ required: true }),
    kind: S({ enum: ['SUPPORT', 'COMPLAINT', 'ADMIN_BROADCAST', 'UNIT'], default: 'SUPPORT', index: true }),
    unitId: ref('units'),
    residentId: ref('residents'),
    complaintId: ref('complaints'),
    participantIds: A(),
    status: S({ enum: ['OPEN', 'CLOSED'], default: 'OPEN', index: true }),
    lastMessageAt: D({ index: true }),
    unreadCounts: X({ default: () => ({}) }),
  }, { indexes: [{ fields: { societyId: 1, kind: 1, status: 1, lastMessageAt: -1 } }] }),

  messages: defineCollection('messages', {
    conversationId: ref('conversations', { required: true }),
    authorId: ref('users', { required: true }),
    authorName: S(),
    authorRole: S(),
    body: S({ required: true }),
    attachments: A(),
    /** Phone numbers are masked in message bodies before persistence (§36). */
    isMasked: B({ default: false }),
    readByUserIds: A(),
    deliveredAt: D(),
  }, {
    softDelete: false,
    indexes: [{ fields: { societyId: 1, conversationId: 1, createdAt: 1 } }],
  }),

  /** Report generation jobs + their downloadable output references (§43). */
  report_jobs: defineCollection('report_jobs', {
    report: S({ required: true }),
    format: S({ enum: ['json', 'csv', 'xlsx', 'pdf'], default: 'csv' }),
    params: X({ default: () => ({}) }),
    status: S({ enum: ['QUEUED', 'RUNNING', 'COMPLETED', 'FAILED'], default: 'QUEUED', index: true }),
    rows: N({ default: 0 }),
    documentId: ref('documents'),
    storageKey: S(),
    error: S(),
    requestedBy: ref('users'),
    startedAt: D(),
    completedAt: D(),
    expiresAt: D(),
  }, { indexes: [{ fields: { societyId: 1, status: 1, createdAt: -1 } }] }),
};
