import {
  ROLES,
  type Role,
  PLATFORM_ROLE_LIST,
  SOCIETY_ROLE_LIST,
} from './roles.js';

/**
 * Permission model
 * ----------------
 * Every protected capability is a `module:action` string. Modules mirror the product
 * surface (and the §73 sidebar), actions mirror the verbs a user can perform.
 *
 * The matrix below declares *default* grants per role. At runtime these defaults are
 * materialised into each society database (`roles` + `role_permissions` collections) so an
 * administrator can add or revoke individual permissions without a code change.
 */

export const PERMISSION_MODULES = [
  'dashboard',
  'society',
  'building',
  'wing',
  'floor',
  'unit',
  'resident',
  'family',
  'vehicle',
  'parking',
  'visitor',
  'delivery',
  'cab',
  'staff',
  'attendance',
  'vendor',
  'workorder',
  'complaint',
  'servicerequest',
  'amenity',
  'amenitybooking',
  'notice',
  'announcement',
  'poll',
  'event',
  'bill',
  'payment',
  'accounting',
  'ledger',
  'expense',
  'document',
  'acknowledgement',
  'emergency',
  'gate',
  'guard',
  'notification',
  'report',
  'audit',
  'setting',
  'search',
  'subscription',
  'supportticket',
  'user',
  'role',
] as const;

export type PermissionModule = (typeof PERMISSION_MODULES)[number];

export const PERMISSION_ACTIONS = [
  'view',
  'create',
  'update',
  'delete',
  'approve',
  'reject',
  'assign',
  'publish',
  'export',
  'generate',
  'refund',
  'cancel',
  'vote',
  'book',
  'acknowledge',
  'record',
  'scan',
  'manage',
] as const;

export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];

export type Permission = `${PermissionModule}:${PermissionAction}`;

export const permission = (module: PermissionModule, action: PermissionAction): Permission =>
  `${module}:${action}` as Permission;

/** `module:*` grants every action on that module. */
export const all = (module: PermissionModule): Permission => `${module}:*` as Permission;

/** Expand a role's declared grants (which may contain `module:*`) into concrete permissions. */
export function expandPermissions(grants: readonly string[]): Set<string> {
  const out = new Set<string>();
  for (const g of grants) {
    const [mod, act] = g.split(':');
    if (!mod) continue;
    if (act === '*') {
      for (const a of PERMISSION_ACTIONS) out.add(`${mod}:${a}`);
    } else if (act) {
      out.add(g);
    }
  }
  return out;
}

/* ------------------------------------------------------------------ *
 * Default role → permission matrix
 * ------------------------------------------------------------------ */

const FULL_SOCIETY_CONSOLE: string[] = [
  all('dashboard'),
  all('society'),
  all('building'),
  all('wing'),
  all('floor'),
  all('unit'),
  all('resident'),
  all('family'),
  all('vehicle'),
  all('parking'),
  all('visitor'),
  all('delivery'),
  all('cab'),
  all('staff'),
  all('attendance'),
  all('vendor'),
  all('workorder'),
  all('complaint'),
  all('servicerequest'),
  all('amenity'),
  all('amenitybooking'),
  all('notice'),
  all('announcement'),
  all('poll'),
  all('event'),
  all('bill'),
  all('payment'),
  all('accounting'),
  all('ledger'),
  all('expense'),
  all('document'),
  all('acknowledgement'),
  all('emergency'),
  all('gate'),
  all('guard'),
  all('notification'),
  all('report'),
  all('audit'),
  all('setting'),
  all('search'),
  all('user'),
  all('role'),
];

const FINANCE_MODULES: string[] = [
  all('bill'),
  all('payment'),
  all('accounting'),
  all('ledger'),
  all('expense'),
  'report:view',
  'report:export',
  'report:generate',
  'unit:view',
  'resident:view',
  'vendor:view',
  'search:view',
  'dashboard:view',
];

const RESIDENT_BASE: string[] = [
  'dashboard:view',
  'society:view',
  'building:view',
  'wing:view',
  'floor:view',
  'unit:view',
  'resident:view',
  'family:view',
  'family:create',
  'family:update',
  'family:delete',
  'vehicle:view',
  'vehicle:create',
  'vehicle:update',
  'vehicle:delete',
  'parking:view',
  'visitor:view',
  'visitor:create',
  'visitor:update',
  'visitor:cancel',
  'visitor:approve',
  'visitor:reject',
  'delivery:view',
  'delivery:approve',
  'delivery:reject',
  'cab:view',
  'cab:create',
  'cab:approve',
  'staff:view',
  'staff:create',
  'staff:update',
  'staff:delete',
  'attendance:view',
  'complaint:view',
  'complaint:create',
  'complaint:update',
  'complaint:cancel',
  'servicerequest:view',
  'servicerequest:create',
  'servicerequest:cancel',
  'amenity:view',
  'amenitybooking:view',
  'amenitybooking:create',
  'amenitybooking:cancel',
  'notice:view',
  'announcement:view',
  'poll:view',
  'poll:vote',
  'event:view',
  'event:book',
  'bill:view',
  'payment:view',
  'payment:create',
  'document:view',
  'document:acknowledge',
  'emergency:create',
  'emergency:view',
  'notification:view',
  'notification:update',
  'search:view',
];

const SECURITY_BASE: string[] = [
  'dashboard:view',
  'society:view',
  'building:view',
  'wing:view',
  'floor:view',
  'unit:view',
  'resident:view',
  'search:view',
  'visitor:view',
  'visitor:create',
  'visitor:update',
  'visitor:record',
  'visitor:scan',
  'visitor:approve',
  'visitor:reject',
  'delivery:view',
  'delivery:create',
  'delivery:update',
  'delivery:record',
  'delivery:scan',
  'cab:view',
  'cab:create',
  'cab:record',
  'cab:scan',
  'staff:view',
  'staff:record',
  'attendance:view',
  'attendance:create',
  'attendance:update',
  'attendance:record',
  'vehicle:view',
  'vehicle:create',
  'vehicle:record',
  'vehicle:scan',
  'parking:view',
  'gate:view',
  'guard:view',
  'emergency:view',
  'emergency:create',
  'emergency:update',
  'amenitybooking:view',
  'amenitybooking:scan',
  'notice:view',
  'notification:view',
  'complaint:view',
  'complaint:create',
];

export const DEFAULT_ROLE_PERMISSIONS: Record<Role, string[]> = {
  /* ---- Platform ---- */
  [ROLES.SUPER_ADMIN]: [
    ...FULL_SOCIETY_CONSOLE,
    all('subscription'),
    all('supportticket'),
  ],
  [ROLES.PLATFORM_ADMIN]: [
    ...FULL_SOCIETY_CONSOLE,
    all('subscription'),
    all('supportticket'),
  ],
  [ROLES.SUPPORT_ADMIN]: [
    'dashboard:view',
    'society:view',
    'society:update',
    all('supportticket'),
    'user:view',
    'audit:view',
    'search:view',
    'notification:view',
    'setting:view',
  ],
  [ROLES.FINANCE_ADMIN]: [
    'dashboard:view',
    'society:view',
    all('subscription'),
    all('payment'),
    all('accounting'),
    all('ledger'),
    all('report'),
    'audit:view',
    'search:view',
  ],

  /* ---- Society ---- */
  [ROLES.SOCIETY_ADMIN]: [...FULL_SOCIETY_CONSOLE],
  [ROLES.CHAIRMAN]: [
    'dashboard:view',
    'society:view',
    'society:update',
    all('notice'),
    all('announcement'),
    all('poll'),
    all('event'),
    all('complaint'),
    all('amenity'),
    all('amenitybooking'),
    all('report'),
    all('document'),
    all('acknowledgement'),
    'resident:view',
    'unit:view',
    'building:view',
    'wing:view',
    'floor:view',
    'visitor:view',
    'bill:view',
    'payment:view',
    'ledger:view',
    'audit:view',
    'search:view',
    'vendor:view',
    'workorder:view',
    'emergency:view',
    'staff:view',
    'setting:view',
    'user:view',
  ],
  [ROLES.SECRETARY]: [
    'dashboard:view',
    'society:view',
    all('notice'),
    all('announcement'),
    all('poll'),
    all('event'),
    all('complaint'),
    all('servicerequest'),
    all('workorder'),
    all('document'),
    all('acknowledgement'),
    all('amenity'),
    all('amenitybooking'),
    all('report'),
    'resident:view',
    'resident:update',
    'family:view',
    'unit:view',
    'building:view',
    'wing:view',
    'floor:view',
    'visitor:view',
    'visitor:export',
    'delivery:view',
    'staff:view',
    'vendor:view',
    'bill:view',
    'payment:view',
    'audit:view',
    'search:view',
    'emergency:view',
    'setting:view',
    'notification:view',
  ],
  [ROLES.TREASURER]: [
    'dashboard:view',
    ...FINANCE_MODULES,
    'vendor:view',
    'vendor:update',
    'workorder:view',
    'audit:view',
    'notice:view',
    'notification:view',
    'setting:view',
  ],
  [ROLES.COMMITTEE_MEMBER]: [
    'dashboard:view',
    'society:view',
    all('poll'),
    all('event'),
    'notice:view',
    'notice:create',
    'announcement:view',
    'complaint:view',
    'complaint:assign',
    'complaint:update',
    'amenity:view',
    'amenitybooking:view',
    'amenitybooking:approve',
    'amenitybooking:reject',
    'resident:view',
    'unit:view',
    'visitor:view',
    'bill:view',
    'payment:view',
    'document:view',
    'document:acknowledge',
    'search:view',
    'report:view',
  ],
  [ROLES.FACILITY_MANAGER]: [
    'dashboard:view',
    'society:view',
    'building:view',
    'building:update',
    'wing:view',
    'floor:view',
    'unit:view',
    'resident:view',
    all('complaint'),
    all('servicerequest'),
    all('workorder'),
    all('vendor'),
    all('staff'),
    all('attendance'),
    all('amenity'),
    all('amenitybooking'),
    all('parking'),
    all('gate'),
    all('guard'),
    'vehicle:view',
    'visitor:view',
    'delivery:view',
    'emergency:view',
    'emergency:update',
    'document:view',
    'document:create',
    'notice:view',
    'notice:create',
    'report:view',
    'report:export',
    'search:view',
    'notification:view',
    'expense:view',
    'expense:create',
    'setting:view',
  ],
  [ROLES.ACCOUNTANT]: [
    'dashboard:view',
    ...FINANCE_MODULES,
    'vendor:view',
    'vendor:update',
    'workorder:view',
    'document:view',
    'document:create',
    'notice:view',
    'notification:view',
  ],
  [ROLES.RECEPTIONIST]: [
    'dashboard:view',
    'society:view',
    'building:view',
    'wing:view',
    'floor:view',
    'unit:view',
    'resident:view',
    all('visitor'),
    all('delivery'),
    all('cab'),
    'staff:view',
    'attendance:view',
    'attendance:create',
    'vehicle:view',
    'parking:view',
    'complaint:view',
    'complaint:create',
    'complaint:assign',
    'amenity:view',
    'amenitybooking:view',
    'amenitybooking:create',
    'notice:view',
    'announcement:view',
    'event:view',
    'emergency:view',
    'emergency:create',
    'search:view',
    'notification:view',
    'document:view',
  ],

  /* ---- Residents ---- */
  [ROLES.OWNER]: [...RESIDENT_BASE, 'poll:create', 'event:create', 'unit:update'],
  [ROLES.TENANT]: [...RESIDENT_BASE],
  [ROLES.FAMILY_MEMBER]: [
    ...RESIDENT_BASE.filter(
      (p) =>
        !p.startsWith('bill:') &&
        !p.startsWith('payment:create') &&
        !p.startsWith('family:') &&
        !p.startsWith('vehicle:create') &&
        !p.startsWith('vehicle:delete') &&
        !p.startsWith('staff:') &&
        !p.startsWith('unit:') &&
        !p.startsWith('poll:create') &&
        !p.startsWith('event:create'),
    ),
    'payment:view',
  ],

  /* ---- Security ---- */
  [ROLES.SECURITY_GUARD]: [...SECURITY_BASE],
  [ROLES.SECURITY_SUPERVISOR]: [
    ...SECURITY_BASE,
    'visitor:delete',
    'visitor:export',
    'delivery:export',
    all('gate'),
    all('guard'),
    'attendance:export',
    'report:view',
    'report:export',
    'emergency:manage',
    'complaint:update',
    'complaint:assign',
    'staff:update',
    'audit:view',
  ],

  /* ---- Staff ---- */
  [ROLES.DOMESTIC_STAFF]: ['dashboard:view', 'attendance:view', 'notification:view', 'unit:view'],
  [ROLES.MAINTENANCE_STAFF]: [
    'dashboard:view',
    'society:view',
    'building:view',
    'wing:view',
    'floor:view',
    'unit:view',
    'resident:view',
    'complaint:view',
    'complaint:update',
    'workorder:view',
    'workorder:update',
    'workorder:record',
    'servicerequest:view',
    'servicerequest:update',
    'attendance:view',
    'notification:view',
    'search:view',
    'amenity:view',
    'document:view',
  ],
  [ROLES.ELECTRICIAN]: [
    'dashboard:view',
    'unit:view',
    'building:view',
    'complaint:view',
    'complaint:update',
    'workorder:view',
    'workorder:update',
    'workorder:record',
    'attendance:view',
    'notification:view',
    'search:view',
  ],
  [ROLES.PLUMBER]: [
    'dashboard:view',
    'unit:view',
    'building:view',
    'complaint:view',
    'complaint:update',
    'workorder:view',
    'workorder:update',
    'workorder:record',
    'attendance:view',
    'notification:view',
    'search:view',
  ],
  [ROLES.HOUSEKEEPING]: [
    'dashboard:view',
    'unit:view',
    'building:view',
    'amenity:view',
    'complaint:view',
    'workorder:view',
    'workorder:update',
    'attendance:view',
    'notification:view',
  ],
  [ROLES.GARDENER]: [
    'dashboard:view',
    'amenity:view',
    'workorder:view',
    'workorder:update',
    'attendance:view',
    'notification:view',
  ],
  [ROLES.DRIVER]: ['dashboard:view', 'unit:view', 'attendance:view', 'notification:view'],

  /* ---- Vendors ---- */
  [ROLES.VENDOR]: [
    'dashboard:view',
    'society:view',
    'unit:view',
    'building:view',
    'workorder:view',
    'workorder:update',
    'workorder:record',
    'complaint:view',
    'complaint:update',
    'servicerequest:view',
    'servicerequest:update',
    'document:view',
    'document:create',
    'notification:view',
    'expense:view',
    'expense:create',
  ],
  [ROLES.SERVICE_PROVIDER]: [
    'dashboard:view',
    'unit:view',
    'workorder:view',
    'workorder:update',
    'servicerequest:view',
    'servicerequest:update',
    'notification:view',
  ],
};

/** Roles that may log into the society management console. */
export const SOCIETY_CONSOLE_ROLES: Role[] = SOCIETY_ROLE_LIST;
/** Roles that may log into the super-admin console. */
export const PLATFORM_CONSOLE_ROLES: Role[] = PLATFORM_ROLE_LIST;

export const PERMISSION_MODULE_LABELS: Record<PermissionModule, string> = {
  dashboard: 'Dashboard',
  society: 'Society',
  building: 'Buildings',
  wing: 'Wings',
  floor: 'Floors',
  unit: 'Units / Flats',
  resident: 'Residents',
  family: 'Family Members',
  vehicle: 'Vehicles',
  parking: 'Parking',
  visitor: 'Visitor Management',
  delivery: 'Deliveries',
  cab: 'Cabs & Drivers',
  staff: 'Staff',
  attendance: 'Attendance',
  vendor: 'Vendors',
  workorder: 'Work Orders',
  complaint: 'Complaints',
  servicerequest: 'Service Requests',
  amenity: 'Amenities',
  amenitybooking: 'Amenity Bookings',
  notice: 'Notices',
  announcement: 'Announcements',
  poll: 'Polls & Voting',
  event: 'Events',
  bill: 'Maintenance Bills',
  payment: 'Payments',
  accounting: 'Accounting',
  ledger: 'Ledgers',
  expense: 'Expenses',
  document: 'Documents',
  acknowledgement: 'Acknowledgements',
  emergency: 'Emergency',
  gate: 'Gates',
  guard: 'Guards & Shifts',
  notification: 'Notifications',
  report: 'Reports',
  audit: 'Audit Logs',
  setting: 'Settings',
  search: 'Global Search',
  subscription: 'Subscriptions & Plans',
  supportticket: 'Support Tickets',
  user: 'Users',
  role: 'Roles & Permissions',
};

export const PERMISSION_ACTION_LABELS: Record<PermissionAction, string> = {
  view: 'View',
  create: 'Create',
  update: 'Update',
  delete: 'Delete',
  approve: 'Approve',
  reject: 'Reject',
  assign: 'Assign',
  publish: 'Publish',
  export: 'Export',
  generate: 'Generate',
  refund: 'Refund',
  cancel: 'Cancel',
  vote: 'Vote',
  book: 'Book',
  acknowledge: 'Acknowledge',
  record: 'Record entry/exit',
  scan: 'Scan QR',
  manage: 'Manage',
};
